# Generated by Django 6.0.6 on 2026-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_databaze',
            name='maxsulot',
            field=models.CharField(choices=[('Elekrtonika', 'Elektronika'), ('musiqa', 'musiqa'), ('mebel', 'mebel')], max_length=250),
        ),
    ]
